[package]
name = "stacks-codec"
version.workspace = true
edition = "2021"
license = "GPL-3.0"
description = "Stack wire format implementation"

[dependencies]
# clarity-vm = { version = "2.3.0",  default-features = false, features = ["canonical", "developer-mode", "log"] }
clarity = { git = "https://github.com/stacks-network/stacks-core.git", branch="feat/clarity-wasm-next", package = "clarity", default-features = false, features = ["canonical", "developer-mode", "log"] }

serde = { version = "1", features = ["derive"] }
wsts = { version = "8.1.0", default-features = false }
