[project]
name = "test-data"
authors = []
description = ""
telemetry = false
requirements = []
cache_dir = "./.cache"

[contracts.contract]
path = "contracts/contract.clar"
clarity_version = 1

[contracts.counter]
path = "contracts/counter.clar"
clarity_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
