[project]
name = 'counter'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []

[contracts.counter]
path = 'contracts/counter.clar'
clarity_version = 2
epoch = 2.4

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
