[package]
name = "clarinet-utils"
version = "1.0.0"
description = "Clarinet helpers"
license = "MIT"
edition = "2021"

[dependencies]
bip39 = "2.2.0"
bip32 = "0.5.3"
libsecp256k1 = { workspace = true }
rand.workspace = true

[lib]
name = "clarinet_utils"
path = "src/lib.rs"
