[package]
name = "clarinet-format"
version = "0.1.0"
edition = "2021"

[dependencies]
# clarity-repl = { path = "../clarity-repl" }
clarity = { workspace = true}

[dev-dependencies]
pretty_assertions = "1.3"

[features]
default = ["cli"]
cli = [
    "clarity/canonical",
    "clarity/developer-mode",
    "clarity/devtools",
    "clarity/log",
]
wasm = [
    "clarity/wasm",
    "clarity/developer-mode",
    "clarity/devtools",
]


[lib]
name = "clarinet_format"
path = "src/lib.rs"
crate-type = ["lib"]
