##
## Auto-opens a PR from main -> develop after a release has been published.
##

name: Open Develop PR

on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:      
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Clarinet
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          base: develop
          branch: main
          title: "chore: update develop branch"
          body: |
            :robot: This is an automated pull request created from a new release in [clarinet](https://github.com/hirosystems/clarinet/releases).

            Updates the develop branch from main.
          assignees: lgalabru
          reviewers: lgalabru
