# The clarinet-sdk is published to npm when a release is created.
# It's based on the npm workspace defined in the package.json at the root of the project.
# Two packages are built with wasm-pack - @hirosystems/clarinet-sdk-wasm and @hirosystems/clarinet-sdk-wasm-browser
# They need to be built first
# Then two packages are built with tsc - @hirosystems/clarinet-sdk and @hirosystems/clarinet-sdk-browser


name: Publish Clarinet SDK
on:
  repository_dispatch:
    types:
      - released
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Rust toolchain
        run: rustup toolchain install stable --profile minimal --component rustfmt --target wasm32-unknown-unknown

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build Wasm packages
        run: npm run build:sdk-wasm

      - name: Publish sdk-wasm package
        run: npm publish -w components/clarinet-sdk-wasm/pkg-node -w components/clarinet-sdk-wasm/pkg-browser --provenance --access public

      - name: Install dependencies
        run: npm ci

      - name: Build sdk package
        run: npm run build:sdk

      - name: Publish sdk package
        run: npm publish -w components/clarinet-sdk/node -w components/clarinet-sdk/browser --provenance --access public
